import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "@/components";
import { Toaster } from "react-hot-toast";
import ProvidersContainer from "./../components/providersContainer/ProvidersContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FeloMart - Your One-Stop Online Shop",
  description: "Generated by FeloMart",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersContainer>
          <Navbar />
          {children}
          <Footer />
        </ProvidersContainer>
        <Toaster />
      </body>
    </html>
  );
}
